import { createContext, useContext, useState, useEffect } from 'react';

const ThemeContext = createContext();

const translations = {
  English: {
    dashboard: 'Dashboard',
    services: 'Services',
    myBookings: 'My Bookings',
    settings: 'Settings',
    logout: 'Logout',
    welcome: 'Welcome',
    farmOverview: 'Here is the overview of your farm activities today.',
    activeBookings: 'Active Bookings',
    pendingRequests: 'Pending Requests',
    recentBookings: 'Recent Bookings',
    noRecentBookings: 'No recent bookings found.',
    discoverServices: 'Discover Services',
    findServices: 'Find the best agricultural services around you.',
    searchServices: 'Search services...',
    bookSpace: 'Book Space',
    booking: 'Booking...',
    successBooked: '✓ Successfully Booked!',
    provider: 'Provider',
    price: 'Price',
    accountSettings: 'Account Settings',
    managePrefs: 'Manage your Krishi Mitra preferences and configurations.',
    profile: 'Profile',
    fullName: 'Full Name',
    emailAddress: 'Email Address',
    role: 'Role',
    saveProfile: 'Save Profile',
    profileSaved: 'Profile Saved!',
    preferences: 'Preferences',
    darkTheme: 'Dark Theme',
    language: 'Language',
    selectedLanguage: 'Selected Language',
    notifications: 'Notifications',
    smsAlerts: 'SMS Alerts',
    emailReports: 'Email Reports',
    bookingAlertsInApp: 'Booking Alerts (In-App)',
    autoSaved: 'Changes are saved automatically and will be reflected immediately.',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    updatePassword: 'Update Password',
    apiIntegrations: 'API Integrations',
    apiDescription: 'External service configurations managed via server environment.',
    connectedActive: 'Connected & Active',
    testMode: 'Test Mode',
    amount: 'Amount',
    scheduledFor: 'Scheduled for',
    pending: 'Pending',
    accepted: 'Accepted',
    rejected: 'Rejected',
    manageBookings: 'Manage your scheduled agricultural services.',
    noBookingsFound: 'No bookings found in your history.',
    loadingSchedule: 'Loading your schedule...',
  },
  Hindi: {
    dashboard: 'डैशबोर्ड',
    services: 'सेवाएं',
    myBookings: 'मेरी बुकिंग',
    settings: 'सेटिंग्स',
    logout: 'लॉग आउट',
    welcome: 'स्वागत है',
    farmOverview: 'यहां आज की आपकी कृषि गतिविधियों का अवलोकन है।',
    activeBookings: 'सक्रिय बुकिंग',
    pendingRequests: 'लंबित अनुरोध',
    recentBookings: 'हालिया बुकिंग',
    noRecentBookings: 'कोई हालिया बुकिंग नहीं मिली।',
    discoverServices: 'सेवाएं खोजें',
    findServices: 'अपने आसपास की सर्वोत्तम कृषि सेवाएं खोजें।',
    searchServices: 'सेवाएं खोजें...',
    bookSpace: 'बुक करें',
    booking: 'बुकिंग हो रही है...',
    successBooked: '✓ सफलतापूर्वक बुक!',
    provider: 'प्रदाता',
    price: 'कीमत',
    accountSettings: 'खाता सेटिंग्स',
    managePrefs: 'अपनी कृषि मित्र प्राथमिकताएं और कॉन्फ़िगरेशन प्रबंधित करें।',
    profile: 'प्रोफ़ाइल',
    fullName: 'पूरा नाम',
    emailAddress: 'ईमेल पता',
    role: 'भूमिका',
    saveProfile: 'प्रोफ़ाइल सहेजें',
    profileSaved: 'प्रोफ़ाइल सहेजी गई!',
    preferences: 'प्राथमिकताएं',
    darkTheme: 'डार्क थीम',
    language: 'भाषा',
    selectedLanguage: 'चयनित भाषा',
    notifications: 'सूचनाएं',
    smsAlerts: 'SMS अलर्ट',
    emailReports: 'ईमेल रिपोर्ट',
    bookingAlertsInApp: 'बुकिंग अलर्ट (इन-ऐप)',
    autoSaved: 'परिवर्तन स्वचालित रूप से सहेजे जाते हैं।',
    changePassword: 'पासवर्ड बदलें',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmNewPassword: 'नया पासवर्ड पुष्टि करें',
    updatePassword: 'पासवर्ड अपडेट करें',
    apiIntegrations: 'API एकीकरण',
    apiDescription: 'सर्वर वातावरण के माध्यम से बाहरी सेवा कॉन्फ़िगरेशन।',
    connectedActive: 'जुड़ा और सक्रिय',
    testMode: 'परीक्षण मोड',
    amount: 'राशि',
    scheduledFor: 'तय तिथि',
    pending: 'लंबित',
    accepted: 'स्वीकृत',
    rejected: 'अस्वीकृत',
    manageBookings: 'अपनी निर्धारित कृषि सेवाओं का प्रबंधन करें।',
    noBookingsFound: 'आपके इतिहास में कोई बुकिंग नहीं मिली।',
    loadingSchedule: 'आपका शेड्यूल लोड हो रहा है...',
  },
  Marathi: {
    dashboard: 'डॅशबोर्ड',
    services: 'सेवा',
    myBookings: 'माझी बुकिंग',
    settings: 'सेटिंग्ज',
    logout: 'लॉग आउट',
    welcome: 'स्वागत आहे',
    farmOverview: 'आजच्या तुमच्या शेती क्रियाकलापांचा आढावा.',
    activeBookings: 'सक्रिय बुकिंग',
    pendingRequests: 'प्रलंबित विनंत्या',
    recentBookings: 'अलीकडील बुकिंग',
    noRecentBookings: 'कोणतीही अलीकडील बुकिंग सापडली नाही.',
    discoverServices: 'सेवा शोधा',
    findServices: 'तुमच्या आसपासच्या सर्वोत्तम कृषी सेवा शोधा.',
    searchServices: 'सेवा शोधा...',
    bookSpace: 'बुक करा',
    booking: 'बुकिंग होत आहे...',
    successBooked: '✓ यशस्वीरित्या बुक!',
    provider: 'प्रदाता',
    price: 'किंमत',
    accountSettings: 'खाते सेटिंग्ज',
    managePrefs: 'तुमच्या कृषी मित्र प्राधान्ये आणि कॉन्फिगरेशन व्यवस्थापित करा.',
    profile: 'प्रोफाइल',
    fullName: 'पूर्ण नाव',
    emailAddress: 'ईमेल पत्ता',
    role: 'भूमिका',
    saveProfile: 'प्रोफाइल जतन करा',
    profileSaved: 'प्रोफाइल जतन केली!',
    preferences: 'प्राधान्ये',
    darkTheme: 'डार्क थीम',
    language: 'भाषा',
    selectedLanguage: 'निवडलेली भाषा',
    notifications: 'सूचना',
    smsAlerts: 'SMS सूचना',
    emailReports: 'ईमेल अहवाल',
    bookingAlertsInApp: 'बुकिंग सूचना (इन-ऍप)',
    autoSaved: 'बदल आपोआप जतन केले जातात.',
    changePassword: 'पासवर्ड बदला',
    currentPassword: 'सध्याचा पासवर्ड',
    newPassword: 'नवीन पासवर्ड',
    confirmNewPassword: 'नवीन पासवर्ड पुष्टी करा',
    updatePassword: 'पासवर्ड अपडेट करा',
    apiIntegrations: 'API एकत्रीकरण',
    apiDescription: 'सर्व्हर वातावरणाद्वारे बाह्य सेवा कॉन्फिगरेशन.',
    connectedActive: 'जोडले आणि सक्रिय',
    testMode: 'चाचणी मोड',
    amount: 'रक्कम',
    scheduledFor: 'नियोजित तारीख',
    pending: 'प्रलंबित',
    accepted: 'स्वीकृत',
    rejected: 'नाकारले',
    manageBookings: 'तुमच्या नियोजित कृषी सेवांचे व्यवस्थापन करा.',
    noBookingsFound: 'तुमच्या इतिहासात कोणतीही बुकिंग सापडली नाही.',
    loadingSchedule: 'तुमचे शेड्यूल लोड होत आहे...',
  },
  Tamil: {
    dashboard: 'டாஷ்போர்டு',
    services: 'சேவைகள்',
    myBookings: 'எனது முன்பதிவுகள்',
    settings: 'அமைப்புகள்',
    logout: 'வெளியேறு',
    welcome: 'வரவேற்கிறோம்',
    farmOverview: 'இன்றைய உங்கள் விவசாய நடவடிக்கைகளின் கண்ணோட்டம்.',
    activeBookings: 'செயலில் உள்ள முன்பதிவுகள்',
    pendingRequests: 'நிலுவையில் உள்ள கோரிக்கைகள்',
    recentBookings: 'சமீபத்திய முன்பதிவுகள்',
    noRecentBookings: 'சமீபத்திய முன்பதிவுகள் இல்லை.',
    discoverServices: 'சேவைகளைக் கண்டறியுங்கள்',
    findServices: 'உங்கள் அருகிலுள்ள சிறந்த விவசாய சேவைகளைக் கண்டறியுங்கள்.',
    searchServices: 'சேவைகளைத் தேடுங்கள்...',
    bookSpace: 'முன்பதிவு செய்',
    booking: 'முன்பதிவு செய்யப்படுகிறது...',
    successBooked: '✓ வெற்றிகரமாக முன்பதிவு!',
    provider: 'வழங்குநர்',
    price: 'விலை',
    accountSettings: 'கணக்கு அமைப்புகள்',
    managePrefs: 'உங்கள் விருப்பத்தேர்வுகளை நிர்வகிக்கவும்.',
    profile: 'சுயவிவரம்',
    fullName: 'முழு பெயர்',
    emailAddress: 'மின்னஞ்சல் முகவரி',
    role: 'பாத்திரம்',
    saveProfile: 'சுயவிவரத்தை சேமி',
    profileSaved: 'சுயவிவரம் சேமிக்கப்பட்டது!',
    preferences: 'விருப்பத்தேர்வுகள்',
    darkTheme: 'இருண்ட தீம்',
    language: 'மொழி',
    selectedLanguage: 'தேர்ந்தெடுக்கப்பட்ட மொழி',
    notifications: 'அறிவிப்புகள்',
    smsAlerts: 'SMS எச்சரிக்கைகள்',
    emailReports: 'மின்னஞ்சல் அறிக்கைகள்',
    bookingAlertsInApp: 'முன்பதிவு எச்சரிக்கைகள் (இன்-ஆப்)',
    autoSaved: 'மாற்றங்கள் தானாக சேமிக்கப்படும்.',
    changePassword: 'கடவுச்சொல்லை மாற்று',
    currentPassword: 'தற்போதைய கடவுச்சொல்',
    newPassword: 'புதிய கடவுச்சொல்',
    confirmNewPassword: 'புதிய கடவுச்சொல்லை உறுதிப்படுத்தவும்',
    updatePassword: 'கடவுச்சொல்லை புதுப்பி',
    apiIntegrations: 'API ஒருங்கிணைப்புகள்',
    apiDescription: 'சர்வர் சூழல் மூலம் வெளிப்புற சேவை உள்ளமைவுகள்.',
    connectedActive: 'இணைக்கப்பட்டு செயலில்',
    testMode: 'சோதனை முறை',
    amount: 'தொகை',
    scheduledFor: 'திட்டமிடப்பட்ட தேதி',
    pending: 'நிலுவையில்',
    accepted: 'ஏற்றுக்கொள்ளப்பட்டது',
    rejected: 'நிராகரிக்கப்பட்டது',
    manageBookings: 'உங்கள் திட்டமிட்ட விவசாய சேவைகளை நிர்வகிக்கவும்.',
    noBookingsFound: 'உங்கள் வரலாற்றில் முன்பதிவுகள் இல்லை.',
    loadingSchedule: 'உங்கள் அட்டவணை ஏற்றப்படுகிறது...',
  },
  Telugu: {
    dashboard: 'డాష్‌బోర్డ్',
    services: 'సేవలు',
    myBookings: 'నా బుకింగ్‌లు',
    settings: 'సెట్టింగ్‌లు',
    logout: 'లాగ్ అవుట్',
    welcome: 'స్వాగతం',
    farmOverview: 'ఈ రోజు మీ వ్యవసాయ కార్యకలాపాల అవలోకనం.',
    activeBookings: 'యాక్టివ్ బుకింగ్‌లు',
    pendingRequests: 'పెండింగ్ అభ్యర్థనలు',
    recentBookings: 'ఇటీవలి బుకింగ్‌లు',
    noRecentBookings: 'ఇటీవలి బుకింగ్‌లు కనుగొనబడలేదు.',
    discoverServices: 'సేవలను కనుగొనండి',
    findServices: 'మీ చుట్టుపక్కల ఉత్తమ వ్యవసాయ సేవలను కనుగొనండి.',
    searchServices: 'సేవలను వెతకండి...',
    bookSpace: 'బుక్ చేయండి',
    booking: 'బుకింగ్ అవుతోంది...',
    successBooked: '✓ విజయవంతంగా బుక్!',
    provider: 'ప్రదాత',
    price: 'ధర',
    accountSettings: 'ఖాతా సెట్టింగ్‌లు',
    managePrefs: 'మీ ప్రాధాన్యతలు మరియు కాన్ఫిగరేషన్‌లను నిర్వహించండి.',
    profile: 'ప్రొఫైల్',
    fullName: 'పూర్తి పేరు',
    emailAddress: 'ఇమెయిల్ చిరునామా',
    role: 'పాత్ర',
    saveProfile: 'ప్రొఫైల్ సేవ్ చేయండి',
    profileSaved: 'ప్రొఫైల్ సేవ్ అయింది!',
    preferences: 'ప్రాధాన్యతలు',
    darkTheme: 'డార్క్ థీమ్',
    language: 'భాష',
    selectedLanguage: 'ఎంచుకున్న భాష',
    notifications: 'నోటిఫికేషన్‌లు',
    smsAlerts: 'SMS హెచ్చరికలు',
    emailReports: 'ఇమెయిల్ నివేదికలు',
    bookingAlertsInApp: 'బుకింగ్ హెచ్చరికలు (ఇన్-యాప్)',
    autoSaved: 'మార్పులు స్వయంచాలకంగా సేవ్ చేయబడతాయి.',
    changePassword: 'పాస్‌వర్డ్ మార్చండి',
    currentPassword: 'ప్రస్తుత పాస్‌వర్డ్',
    newPassword: 'కొత్త పాస్‌వర్డ్',
    confirmNewPassword: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
    updatePassword: 'పాస్‌వర్డ్ అప్‌డేట్ చేయండి',
    apiIntegrations: 'API ఇంటిగ్రేషన్లు',
    apiDescription: 'సర్వర్ ఎన్విరాన్మెంట్ ద్వారా బాహ్య సేవా కాన్ఫిగరేషన్లు.',
    connectedActive: 'కనెక్ట్ అయి యాక్టివ్',
    testMode: 'టెస్ట్ మోడ్',
    amount: 'మొత్తం',
    scheduledFor: 'షెడ్యూల్ తేదీ',
    pending: 'పెండింగ్',
    accepted: 'ఆమోదించబడింది',
    rejected: 'తిరస్కరించబడింది',
    manageBookings: 'మీ షెడ్యూల్డ్ వ్యవసాయ సేవలను నిర్వహించండి.',
    noBookingsFound: 'మీ చరిత్రలో బుకింగ్‌లు కనుగొనబడలేదు.',
    loadingSchedule: 'మీ షెడ్యూల్ లోడ్ అవుతోంది...',
  },
};

export const ThemeProvider = ({ children }) => {
  const [isDark, setIsDark] = useState(() => {
    return localStorage.getItem('km_darkTheme') !== 'false';
  });

  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('km_language') || 'English';
  });

  // Apply theme to the root HTML element
  useEffect(() => {
    const root = document.documentElement;
    if (isDark) {
      root.classList.add('dark');
      root.classList.remove('light');
    } else {
      root.classList.add('light');
      root.classList.remove('dark');
    }
    localStorage.setItem('km_darkTheme', isDark);
  }, [isDark]);

  useEffect(() => {
    localStorage.setItem('km_language', language);
  }, [language]);

  const toggleTheme = () => setIsDark(prev => !prev);

  // Translation helper
  const t = (key) => {
    const lang = translations[language] || translations['English'];
    return lang[key] || translations['English'][key] || key;
  };

  return (
    <ThemeContext.Provider value={{ isDark, toggleTheme, language, setLanguage, t }}>
      {children}
    </ThemeContext.Provider>
  );
};

export const useTheme = () => useContext(ThemeContext);
